#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            ref class Style;
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
            }
        }
    }
}

namespace flowchart
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class GridPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Style^ RECTANGLE_STYLE;
        private: ::Windows::UI::Xaml::Style^ BUTTON_STYLE_CONNECTOR;
        private: ::Windows::UI::Xaml::Style^ BUTTON_STYLE_CONTENTS;
        private: ::Windows::UI::Xaml::Style^ BUTTON_STYLE_DETAIL;
        private: ::Windows::UI::Xaml::Style^ IMAGE_PROCESS;
        private: ::Windows::UI::Xaml::Style^ IMAGE_DECISION;
        private: ::Windows::UI::Xaml::Style^ IMAGE_PREPARATION;
        private: ::Windows::UI::Xaml::Style^ IMAGE_TERMINATOR;
        private: ::Windows::UI::Xaml::Style^ IMAGE_DATA;
        private: ::Windows::UI::Xaml::Style^ IMAGE_DOCUMENT;
        private: ::Windows::UI::Xaml::Controls::Grid^ PageGrid;
    };
}

