//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "MainPage.xaml.h"

void ::flowchart::MainPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::flowchart::MainPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                this->s6 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->s6))->DragStarting += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::UIElement^, ::Windows::UI::Xaml::DragStartingEventArgs^>(this, (void (::flowchart::MainPage::*)
                    (::Windows::UI::Xaml::UIElement^, ::Windows::UI::Xaml::DragStartingEventArgs^))&MainPage::Image_DragStarting);
                (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->s6))->DropCompleted += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::UIElement^, ::Windows::UI::Xaml::DropCompletedEventArgs^>(this, (void (::flowchart::MainPage::*)
                    (::Windows::UI::Xaml::UIElement^, ::Windows::UI::Xaml::DropCompletedEventArgs^))&MainPage::Image_DropCompleted);
            }
            break;
        case 2:
            {
                this->s5 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->s5))->DragStarting += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::UIElement^, ::Windows::UI::Xaml::DragStartingEventArgs^>(this, (void (::flowchart::MainPage::*)
                    (::Windows::UI::Xaml::UIElement^, ::Windows::UI::Xaml::DragStartingEventArgs^))&MainPage::Image_DragStarting);
                (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->s5))->DropCompleted += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::UIElement^, ::Windows::UI::Xaml::DropCompletedEventArgs^>(this, (void (::flowchart::MainPage::*)
                    (::Windows::UI::Xaml::UIElement^, ::Windows::UI::Xaml::DropCompletedEventArgs^))&MainPage::Image_DropCompleted);
            }
            break;
        case 3:
            {
                this->s4 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->s4))->DragStarting += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::UIElement^, ::Windows::UI::Xaml::DragStartingEventArgs^>(this, (void (::flowchart::MainPage::*)
                    (::Windows::UI::Xaml::UIElement^, ::Windows::UI::Xaml::DragStartingEventArgs^))&MainPage::Image_DragStarting);
                (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->s4))->DropCompleted += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::UIElement^, ::Windows::UI::Xaml::DropCompletedEventArgs^>(this, (void (::flowchart::MainPage::*)
                    (::Windows::UI::Xaml::UIElement^, ::Windows::UI::Xaml::DropCompletedEventArgs^))&MainPage::Image_DropCompleted);
            }
            break;
        case 4:
            {
                this->s3 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->s3))->DragStarting += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::UIElement^, ::Windows::UI::Xaml::DragStartingEventArgs^>(this, (void (::flowchart::MainPage::*)
                    (::Windows::UI::Xaml::UIElement^, ::Windows::UI::Xaml::DragStartingEventArgs^))&MainPage::Image_DragStarting);
                (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->s3))->DropCompleted += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::UIElement^, ::Windows::UI::Xaml::DropCompletedEventArgs^>(this, (void (::flowchart::MainPage::*)
                    (::Windows::UI::Xaml::UIElement^, ::Windows::UI::Xaml::DropCompletedEventArgs^))&MainPage::Image_DropCompleted);
            }
            break;
        case 5:
            {
                this->s2 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->s2))->DragStarting += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::UIElement^, ::Windows::UI::Xaml::DragStartingEventArgs^>(this, (void (::flowchart::MainPage::*)
                    (::Windows::UI::Xaml::UIElement^, ::Windows::UI::Xaml::DragStartingEventArgs^))&MainPage::Image_DragStarting);
                (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->s2))->DropCompleted += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::UIElement^, ::Windows::UI::Xaml::DropCompletedEventArgs^>(this, (void (::flowchart::MainPage::*)
                    (::Windows::UI::Xaml::UIElement^, ::Windows::UI::Xaml::DropCompletedEventArgs^))&MainPage::Image_DropCompleted);
            }
            break;
        case 6:
            {
                this->s1 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->s1))->DragStarting += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::UIElement^, ::Windows::UI::Xaml::DragStartingEventArgs^>(this, (void (::flowchart::MainPage::*)
                    (::Windows::UI::Xaml::UIElement^, ::Windows::UI::Xaml::DragStartingEventArgs^))&MainPage::Image_DragStarting);
                (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->s1))->DropCompleted += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::UIElement^, ::Windows::UI::Xaml::DropCompletedEventArgs^>(this, (void (::flowchart::MainPage::*)
                    (::Windows::UI::Xaml::UIElement^, ::Windows::UI::Xaml::DropCompletedEventArgs^))&MainPage::Image_DropCompleted);
            }
            break;
        case 7:
            {
                this->GridContentFrame = safe_cast<::Windows::UI::Xaml::Controls::Frame^>(__target);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::flowchart::MainPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


